version: '3'
services:
  influxdb:
    image: "influxdb:latest"
    container_name: influxdb
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      # UDP Port
      - "8089:8089"

  chronograf:
    image: "chronograf:latest"
    container_name: chronograf
    volumes:
      - ./chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb

  mosquitto:
    image: "eclipse-mosquitto:latest"
    container_name: mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  data_loader:
    image: "data_loader:latest"
    container_name: data_loader
    build: ./loader
    environment:
      INFLUX_HOST: influxdb
      MQTT_HOST: mosquitto
    depends_on:
      - influxdb
      - mosquitto
